# Review Python

## Variables & Data Types

In [8]:
score = 95
weight = 68.5
course = 'DGA306'
is_student = True

In [9]:
print("score =", score, "| type:", type(score))
print("weight =", weight, "| type:", type(weight))
print("course =", course, "| type:", type(course))
print("is_student =", is_student, "| type:", type(is_student))

score = 95 | type: <class 'int'>
weight = 68.5 | type: <class 'float'>
course = DGA306 | type: <class 'str'>
is_student = True | type: <class 'bool'>

### Type Casting (การแปลงชนิดข้อมูล)

In [ ]:
score_str = "95"
score_int = int(score_str)  # แปลงจาก string เป็น integer
print(score_int)
type(score_int)

95

int

In [6]:
height_int = 175
height_float = float(height_int)  # แปลงจาก integer เป็น float
print(height_float)
type(height_float)

175.0

float

In [10]:
year_int = 2026
year_str = str(year_int)
print(year_str)
type(year_str)

2026

str

In [ ]:
# Playground

## String Operations

ตัวอย่างการนับ Index

| ตำแหน่งตัวอักษร | H | e | l | l | o |
|---|---|---|---|---|---|
| Index | 0 | 1 | 2 | 3 | 4 |

In [14]:
text = "Hello"

In [ ]:
print("ตัวที่ 0:", text[0])    # H
print("ตัวสุดท้าย:", text[-1]) # o

ตัวที่ 0: H
ตัวสุดท้าย: o

### Slicing
> Syntax:
```string[start : end : step]```
> - `step` defines how many characters to skip.

In [23]:
print("0:5  ->", text[0:5])   # Hello
print("1:   ->", text[1:])    # ello
print(":2   ->", text[:2])    # He
print('----------')
print("0:5:2 ->", text[0:5:2]) # Hlo
# or
print("::2  ->", text[::2])   # Hlo

0:5  -> Hello
1:   -> ello
:2   -> He
----------
0:5:2 -> Hlo
::2  -> Hlo

### More String Methods

In [27]:
course_name = "  DGA306 : Data Analytics Techniques  "

print(course_name.upper())       # ตัวพิมพ์ใหญ่ทั้งหมด
print(course_name.lower())       # ตัวพิมพ์เล็กทั้งหมด
print(course_name.capitalize())  # ตัวแรกเป็นตัวพิมพ์ใหญ่
print(course_name.strip())       # ตัดช่องว่างหัวท้าย
print(course_name.replace("DGA306", "Course Name"))  # แทนที่คำ

  DGA306 : DATA ANALYTICS TECHNIQUES
  dga306 : data analytics techniques
  dga306 : data analytics techniques
DGA306 : Data Analytics Techniques
  Course Name : Data Analytics Techniques

In [ ]:
string1 = "DGA"
string2 = "306"
result = string1 + string2
adding_space = string1 + " " + string2 # เพิ่มช่องว่างเข้าไประหว่างคำที่ 1 และ 2
print(result)
print(adding_space)

DGA306
DGA 306

In [47]:
print("Hello\nWorld") # Hello (ขึ้นบรรทัดใหม่) World

Hello
World

In [48]:
print(len(course_name)) # คืนค่าความยาวของ string นั้น ๆ

38

In [21]:
email = "user@example.com"
parts = email.split("@")   # แบ่ง string ด้วย @

print("parts:", parts)
print("username:", parts[0])
print("domain:", parts[1])

parts: ['user', 'example.com']
username: user
domain: example.com

In [22]:
# String formatting
score = 88.567
print("คะแนน: %.2f" % score)          # ทศนิยม 2 ตำแหน่ง
print(f"คะแนน: {score:.2f}")

คะแนน: 88.57
คะแนน: 88.57

In [ ]:
# Playground

## List, Tuple, Set, Dictionary

| ชนิด | วิธีสร้าง | Mutable (เปลี่ยนค่าภายในได้) | มีค่าซ้ำได้ |
|------|-------|------------|---------|
| List | `[...]` | Yes | Yes |
| Tuple | `(...)` | No | Yes |
| Set | `{...}` | Yes | No |
| Dictionary | `{"key": val}` | Yes | key ไม่สามารถซ้ำกันได้ |

### List

In [49]:
fruits = ["apple", "banana", "cherry", "apple"]

In [51]:
print("List:", fruits)
print("สมาชิกตัวที่ 1:", fruits[1])
print("Slicing [1:3]:", fruits[1:3])

List: ['apple', 'banana', 'cherry', 'apple']
สมาชิกตัวที่ 1: banana
Slicing [1:3]: ['banana', 'cherry']

In [ ]:
fruits.append("durian")   # เพิ่มทุเรียนเข้าไปต่อท้ายใน list
print(fruits)

['apple', 'banana', 'cherry', 'apple', 'durian']

In [39]:
fruits.insert(0, "avocado")  # เพิ่ม avocado เข้าไปที่ตำแหน่ง 0
print(fruits)

['avocado', 'apple', 'banana', 'cherry', 'apple', 'durian']

In [40]:
fruits.remove("apple")    # ลบค่าแรกที่เจอ
print("final list:", fruits)

final list: ['avocado', 'banana', 'cherry', 'apple', 'durian']

In [41]:
scores = [85, 92, 78, 65, 90]

print("max:", max(scores))
print("min:", min(scores))
print("sum:", sum(scores))
print("sorted:", sorted(scores, reverse=True))

max: 92
min: 65
sum: 410
sorted: [92, 90, 85, 78, 65]

(เสริม) Nested List

In [55]:
matrix = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

In [56]:
print(matrix[0])       # [1, 2, 3]
print(matrix[1][2])    # 6  (row 1, col 2)
print(matrix[2][0])    # 7

[1, 2, 3]
6
7

In [54]:
for row in matrix:
    for val in row:
        print(val, end=" ")
    print()

1 2 3
4 5 6
7 8 9

### Tuple

In [59]:
coordinates = (13.7563, 100.5018)
print("Tuple:", coordinates)
print("lat:", coordinates[0])

Tuple: (13.7563, 100.5018)
lat: 13.7563

In [ ]:
# Concatenation
t1 = (1, 2, 3)
t2 = (4, 5, 6)
res = t1 + t2
print(res)

(1, 2, 3, 4, 5, 6)

In [68]:
sliced_tuple = res[0:5:2]
print(sliced_tuple)

(1, 3, 5)

(เสริม) Nested Tuple

In [69]:
locations = (
    ("Bangkok",    13.7563, 100.5018),
    ("ChiangMai",  18.7883, 98.9853),
    ("Phuket",      7.8804, 98.3923)
)

In [70]:
print(locations[0])        # ("Bangkok", 13.7563, 100.5018)
print(locations[1][0])     # ChiangMai
print(locations[2][1])     # 7.8804

('Bangkok', 13.7563, 100.5018)
ChiangMai
7.8804

In [71]:
for city, lat, lon in locations:
    print(f"{city}: ({lat}, {lon})")

Bangkok: (13.7563, 100.5018)
ChiangMai: (18.7883, 98.9853)
Phuket: (7.8804, 98.3923)

### Set

In [85]:
tags = {"python", "data", "python", "analytics", "data"}
print("Set:", tags)

Set: {'python', 'analytics', 'data'}

In [87]:
tags.add('Computer')
tags.update(['test', 'course'])
print("Current Set:", tags)

Current Set: {'python', 'analytics', 'course', 'test', 'data', 'Computer'}

In [88]:
tags.remove('data')
print("Current Set:", tags)

Current Set: {'python', 'analytics', 'course', 'test', 'Computer'}

In [45]:
a = {1, 2, 3, 4}
b = {3, 4, 5, 6}
print("Union :", a | b)
print("Intersection :", a & b)

Union : {1, 2, 3, 4, 5, 6}
Intersection : {3, 4}

การเปลี่ยนจาก List เป็น Set

In [ ]:
list1 = [10, 20, 30, 30, 40, 50, 60, 60]
new_set = set(list1)
print(new_set)

{40, 10, 50, 20, 60, 30}

### Dictionary

In [72]:
student = {
    "id": "ST001",
    "name": "Alice",
    "gpa": 3.8,
    "courses": ["Python", "Statistics"]
}

In [73]:
print("ชื่อ:", student["name"])
print("GPA:", student["gpa"])
print("วิชา:", student["courses"])

ชื่อ: Alice
GPA: 3.8
วิชา: ['Python', 'Statistics']

In [ ]:
student["year"] = 2        # เพิ่ม key ใหม่
student["gpa"] = 3.9       # แก้ไขค่า GPA
del student["id"]          # ลบ key

In [75]:
for key, value in student.items():
    print(f"  {key}: {value}")

  name: Alice
  gpa: 3.9
  courses: ['Python', 'Statistics']
  year: 2

(เสริม) Nested Dictionary

In [91]:
employees = {
    "E001": {"name": "Alice", "dept": "IT",      "salary": 55000},
    "E002": {"name": "Bob",   "dept": "HR",      "salary": 48000},
    "E003": {"name": "Carol", "dept": "Finance", "salary": 62000},
}

In [92]:
print(employees["E001"])             # {'name': 'Alice', ...}
print(employees["E002"]["name"])     # Bob
print(employees["E003"]["salary"])   # 62000

{'name': 'Alice', 'dept': 'IT', 'salary': 55000}
Bob
62000

In [93]:
# แก้ไขค่าข้างใน
employees["E001"]["salary"] = 58000

# เพิ่ม employee ใหม่
employees["E004"] = {"name": "David", "dept": "IT", "salary": 71000}

In [94]:
for emp_id, info in employees.items():
    print(f"{emp_id}: {info['name']} ({info['dept']}) — {info['salary']:,} บาท")

E001: Alice (IT) — 58,000 บาท
E002: Bob (HR) — 48,000 บาท
E003: Carol (Finance) — 62,000 บาท
E004: David (IT) — 71,000 บาท

In [ ]:
# Playground

## Conditions & Branching

### Comparison Operators

In [97]:
print(5 == 5)   # Equal
print(5 == 10)  # Result should be false

True
False

In [98]:
print(5 != 3)   # Not equal
print(5 != 5)   # Result should be false

True
False

In [99]:
print(7 > 4)    # Greater than
print(3 < 8)    # Less than

# Result should be false
print(7 < 4)
print(3 > 8)

True
True
False
False

In [100]:
print(9 >= 6)   # Greater or equal
print(2 <= 5)   # Less or equal

True
True

### If, else, elif

In [108]:
score = 85

if score >= 80:
    print("เกรด A")

เกรด A

In [109]:
score = 72

if score >= 80:
    print("เกรด A")
else:
    print("รอการพิจารณาเพิ่มเติม")

รอการพิจารณาเพิ่มเติม

In [112]:
score = 75

if score >= 80:
    grade = A
elif score >= 70:
    grade = "B"
elif score >= 60:
    grade = "C"
elif score >= 50:
    grade = "D"
else:
    grade = "F"

print("เกรดที่ได้:", grade)

เกรดที่ได้: B

### and, or, not

and : ต้องผ่านทั้ง 2 เงื่อนไข

In [114]:
age = 22
has_id = True
if age >= 18 and has_id:
    print("ผ่านเงื่อนไขที่กำหนด")

ผ่านเงื่อนไขที่กำหนด

or : ผ่านเงื่อนไขใดเงื่อนไขหนึ่ง

In [116]:
is_holiday = False
is_weekend = True
if is_holiday or is_weekend:
    print("หยุด!")

หยุด!

not : กลับค่านั้น เช่น จาก True จะกลายเป็น False

In [117]:
is_raining = False
if not is_raining:
    print("ออกไปเดินเล่นได้")

ออกไปเดินเล่นได้

In [ ]:
# Playground

## Loops

### for loop

In [118]:
grades = ["A", "B", "C"]

In [125]:
for grade in grades:
    print("Grade:", grade)

Grade: A
Grade: B
Grade: C

In [126]:
for i in range(1, 9):        # 1 ถึง 5
    print(i)

1
2
3
4
5
6
7
8

In [127]:
for i in range(20, 0, -4):   # 10, 8, 6, 4, 2
    print(i, end=" ")

20 16 12 8 4

In [129]:
for idx, grade in enumerate(grades, start=1):
    print(f"{idx}. {grade}")

1. A
2. B
3. C

### while loop

In [130]:
# นับถอยหลัง
count = 5
while count > 0:
    print(count, end=" ")
    count -= 1
print("Time out")

5 4 3 2 1 Time out

In [132]:
# สะสมค่าจนกว่าจะถึงเป้า
total = 0
numbers = [10, 25, 8, 42, 15, 30]

i = 0
while total < 95 and i < len(numbers):
    total += numbers[i]
    print(f"  เพิ่ม {numbers[i]} => รวม {total}")
    i += 1
print(f"หยุดที่ index {i}, รวม = {total}")

  เพิ่ม 10 => รวม 10
  เพิ่ม 25 => รวม 35
  เพิ่ม 8 => รวม 43
  เพิ่ม 42 => รวม 85
  เพิ่ม 15 => รวม 100
หยุดที่ index 5, รวม = 100

In [ ]:
# Playground

## Functions

ตัวอย่าง function เล็ก ๆ น้อย ๆ

In [1]:
def calculate_bmi(weight, height_cm):
    """คำนวณ BMI และคืนค่าสถานะ"""
    height_m = height_cm / 100
    bmi = weight / (height_m ** 2)

    if bmi < 18.5:
        status = "Underweight"
    elif bmi < 25:
        status = "Normal"
    elif bmi < 30:
        status = "Overweight"
    else:
        status = "Obese"

    return round(bmi, 2), status

In [2]:
bmi_val, bmi_status = calculate_bmi(70, 175)
print(f"BMI: {bmi_val}\nStatus: {bmi_status}")

BMI: 22.86
Status: Normal

In [4]:
def power(base, exponent=2):
    """ยกกำลัง — exponent default คือ 2"""
    return base ** exponent

print(power(3))     # 3^2 = 9
print(power(3, 3))  # 3^3 = 27
print(power(2, 10)) # 2^10 = 1024

9
27
1024

lambda

In [5]:
square = lambda x: x ** 2
add = lambda x, y: x + y

print(square(5))
print(add(3, 7))

25
10

In [ ]:
# Playground

## Class

**Class** คือแม่พิมพ์ หรือ blueprint สำหรับสร้างสิ่งของ  
**Object** คือสิ่งของที่สร้างขึ้นมาจาก Class นั้น

ตัวอย่าง เช่น Class Student สำหรับเก็บข้อมูลและวิเคราะห์นักเรียน

In [9]:
class Student:
    def __init__(self, student_id, name, scores):
        self.student_id = student_id
        self.name       = name
        self.scores     = scores  # list ของคะแนน

    def average(self):
        return sum(self.scores) / len(self.scores)

    def grade(self):
        avg = self.average()
        if avg >= 80: return "A"
        elif avg >= 70: return "B"
        elif avg >= 60: return "C"
        elif avg >= 50: return "D"
        else: return "F"

    def report(self):
        print(f"[{self.student_id}] {self.name}")
        print(f"  คะแนน: {self.scores}")
        print(f"  เฉลี่ย: {self.average():.1f} \n  เกรด: {self.grade()}")

In [10]:
# สร้างนักเรียนหลายคน
students = [
    Student("ST001", "Alice",  [85, 90, 78, 92]),
    Student("ST002", "Bob",    [70, 65, 72, 68]),
    Student("ST003", "Carol",  [95, 88, 91, 97]),
]

In [12]:
for s in students:
    s.report()
    print()

# หาคนที่คะแนนสูงที่สุด
best_student = students[0]          # สมมติคนแรกดีที่สุดก่อน
for s in students:
    if s.average() > best_student.average():
        best_student = s            # ถ้าเจอคนที่ดีกว่า ให้อัปเดต

print(f"คะแนนสูงสุด: {best_student.name} ({best_student.average():.1f})")

[ST001] Alice
  คะแนน: [85, 90, 78, 92]
  เฉลี่ย: 86.2
  เกรด: A

[ST002] Bob
  คะแนน: [70, 65, 72, 68]
  เฉลี่ย: 68.8
  เกรด: C

[ST003] Carol
  คะแนน: [95, 88, 91, 97]
  เฉลี่ย: 92.8
  เกรด: A

คะแนนสูงสุด: Carol (92.8)

# pandas

In [24]:
import pandas as pd
import numpy as np

In [25]:
# สร้าง DataFrame จาก Dictionary
data = {
    "name":       ["Alice", "Bob", "Carol", "David", "Eve", "Frank"],
    "department": ["IT", "HR", "IT", "Finance", "HR", "Finance"],
    "age":        [28, 35, 31, 29, 42, 38],
    "salary":     [55000, 48000, 62000, 71000, 53000, 68000],
    "experience": [4, 8, 6, 5, 15, 11]
}
df = pd.DataFrame(data)

df

    name department  age  salary  experience
0  Alice         IT   28   55000           4
1    Bob         HR   35   48000           8
2  Carol         IT   31   62000           6
3  David    Finance   29   71000           5
4    Eve         HR   42   53000          15
5  Frank    Finance   38   68000          11

In [27]:
print("shape:", df.shape)          # (rows, cols)
print()

print("dtypes:")
print(df.dtypes)                    # ชนิดข้อมูลแต่ละคอลัมน์
print()

shape: (6, 5)

dtypes:
name          object
department    object
age            int64
salary         int64
experience     int64
dtype: object

head(3) คือ ดูข้อมูล 3 แถวแรก

In [26]:
df.head(3)

    name department  age  salary  experience
0  Alice         IT   28   55000           4
1    Bob         HR   35   48000           8
2  Carol         IT   31   62000           6

tail(2) คือ ดูข้อมูล 2 แถวท้าย

In [28]:
df.tail(2)

    name department  age  salary  experience
4    Eve         HR   42   53000          15
5  Frank    Finance   38   68000          11

describe() ดูสถิติพื้นฐาน

In [29]:
df.describe()

             age        salary  experience
count   6.000000      6.000000    6.000000
mean   33.833333  59500.000000    8.166667
std     5.492419   9005.553842    4.167333
min    28.000000  48000.000000    4.000000
25%    29.500000  53500.000000    5.250000
50%    33.000000  58500.000000    7.000000
75%    37.250000  66500.000000   10.250000
max    42.000000  71000.000000   15.000000

info() ดูโครงสร้างข้อมูล

In [30]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        6 non-null      object
 1   department  6 non-null      object
 2   age         6 non-null      int64
 3   salary      6 non-null      int64
 4   experience  6 non-null      int64
dtypes: int64(3), object(2)
memory usage: 368.0+ bytes

เลือกดูคอลัมน์

In [32]:
df["salary"] # คอลัมน์เดียว

0    55000
1    48000
2    62000
3    71000
4    53000
5    68000
Name: salary, dtype: int64

In [34]:
# หลายคอลัมน์
df[["name", "salary", "department"]]

    name  salary department
0  Alice   55000         IT
1    Bob   48000         HR
2  Carol   62000         IT
3  David   71000    Finance
4    Eve   53000         HR
5  Frank   68000    Finance

### Filtering

In [35]:
# กรองพนักงาน IT
it_dept = df[df["department"] == "IT"]
it_dept

    name department  age  salary  experience
0  Alice         IT   28   55000           4
2  Carol         IT   31   62000           6

In [36]:
# กรองเงินเดือน > 60000
high_salary = df[df["salary"] > 60000]
high_salary[["name", "department", "salary"]]

    name department  salary
2  Carol         IT   62000
3  David    Finance   71000
5  Frank    Finance   68000

In [ ]:
# ตัวอย่างการกรองแบบหลายเงื่อนไข (& = and, | = or)
# ในที่นี้คือ การกรองพนักงาน IT ที่มีประสบการณ์มากกว่าหรือเท่ากับ 5 ปี
senior_it = df[(df["department"] == "IT") & (df["experience"] >= 5)]
senior_it

    name department  age  salary  experience
2  Carol         IT   31   62000           6

### Sorting

In [39]:
# เรียงตาม salary มากไปน้อย
df.sort_values("salary", ascending=False)

    name department  age  salary  experience
3  David    Finance   29   71000           5
5  Frank    Finance   38   68000          11
2  Carol         IT   31   62000           6
0  Alice         IT   28   55000           4
4    Eve         HR   42   53000          15
1    Bob         HR   35   48000           8

In [40]:
# เรียงหลายคอลัมน์
# ในที่นี้คือเรียงตาม department แล้ว salary
df.sort_values(["department", "salary"], ascending=[True, False])

    name department  age  salary  experience
3  David    Finance   29   71000           5
5  Frank    Finance   38   68000          11
4    Eve         HR   42   53000          15
1    Bob         HR   35   48000           8
2  Carol         IT   31   62000           6
0  Alice         IT   28   55000           4

### Group by & Aggregation

In [41]:
# ตัวอย่างการหาเงินเดือนเฉลี่ยต่อแผนก
df.groupby("department")["salary"].mean().round(0)

department
Finance    69500.0
HR         50500.0
IT         58500.0
Name: salary, dtype: float64

In [42]:
# ตัวอย่างการสรุปสถิติต่อแผนก
df.groupby("department").agg({
    "salary":     ["mean", "max", "min"],
    "experience": "mean",
    "name":       "count"
}).round(1)

             salary               experience  name
               mean    max    min       mean count
department
Finance     69500.0  71000  68000        8.0     2
HR          50500.0  53000  48000       11.5     2
IT          58500.0  62000  55000        5.0     2

### Adding & Modifying Columns

In [45]:
df["salary_k"] = (df["salary"] / 1000).round(1)  # เพิ่มคอลัมน์ salary ในหน่วย k

In [46]:
df

    name department  age  salary  experience  salary_k
0  Alice         IT   28   55000           4      55.0
1    Bob         HR   35   48000           8      48.0
2  Carol         IT   31   62000           6      62.0
3  David    Finance   29   71000           5      71.0
4    Eve         HR   42   53000          15      53.0
5  Frank    Finance   38   68000          11      68.0

In [47]:
# สร้าง function เพื่อแบ่ง salary ออกเป็นระดับต่าง ๆ
def label_salary(s):
    if s >= 65000: return "High"
    elif s >= 55000: return "Mid"
    else: return "Low"

df["salary_level"] = df["salary"].apply(label_salary)

In [48]:
df

    name department  age  salary  experience  salary_k salary_level
0  Alice         IT   28   55000           4      55.0          Mid
1    Bob         HR   35   48000           8      48.0          Low
2  Carol         IT   31   62000           6      62.0          Mid
3  David    Finance   29   71000           5      71.0         High
4    Eve         HR   42   53000          15      53.0          Low
5  Frank    Finance   38   68000          11      68.0         High